name: Build Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Package
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 16
      - name: Install yarn
        run:  npm install --global yarn
      - name: Install Electron Packager
        run: npm i -g electron-packager
      - name: Install Electron Installer Debian
        run: npm i -g electron-installer-debian
      - name: Install fakeroot
        run: sh scripts/install.sh
      - name: Install node modules
        run:  npm i --legacy-peer-deps
      - name: create .env file
        run: touch scripts/.env
      - name: Add Enviornment veriable
        run:  echo "NODE_ENV:${{ secrets.NODE_ENV }}"  >> scripts/.env
              echo "MAIN_URL:${{ secrets.MAIN_URL }}" >> scripts/.env
              echo "MAIN_URL:${{ secrets.API_VERSION }}" >> scripts/.env
              echo "MARKET_SLUG:${{ secrets.MARKET_SLUG }}" >> scripts/.env
              echo "USER_AGENT_PRODUCT:${{ secrets.USER_AGENT_PRODUCT }}" >> scripts/.env
              echo "INTERNAL_TCP_SERVER_PORT:${{ secrets.INTERNAL_TCP_SERVER_PORT }}" >> scripts/.env
              echo "DISPLAY:${{ secrets.DISPLAY }}" >> scripts/.env
              echo "PORT:${{ secrets.PORT }}" >> scripts/.env
              echo "SENTRY_DSN:${{ secrets.SENTRY_DSN }}" >> scripts/.env
              echo "DEFAULT_EXTERNAL_TCP_CUES_PORT:${{ secrets.DEFAULT_EXTERNAL_TCP_CUES_PORT }}" >> scripts/.env

      - name: Run build
        run:  npm run build:linux
      - name: Package
        run: npm run package:linux 
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: | 
             build/app/release-builds/installers
    
