name: Build Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Package
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 16
      - name: Install yarn
        run:  npm install --global yarn
      - name: Install Electron Packager
        run: npm i -g electron-packager
      - name: Install Electron Installer Debian
        run: npm i -g electron-installer-debian
      - name: Install fakeroot
        run: sh scripts/install.sh
      - name: Install node modules
        run:  npm i --legacy-peer-deps
      - name: Add Enviornment veriable
        with:
           node_env: ${{ secrets.NODE_ENV }}
           main_url: ${{ secrets.MAIN_URL }}
           api_version: ${{ secrets.API_VERSION }}
           base_url: ${{ secrets.BASE_URL }}
           market_slug: ${{ secrets.MARKET_SLUG }}
           user_agent_product: ${{ secrets.USER_AGENT_PRODUCT }}
           internal_tcp_server_port: ${{ secrets.INTERNAL_TCP_SERVER_PORT }}
           display: ${{ secrets.DISPLAY }}
           port: ${{ secrets.PORT }}
           sentry_dsn: ${{ secrets.SENTRY_DSN }}
           default_external_tcp_cues_port: ${{ secrets.DEFAULT_EXTERNAL_TCP_CUES_PORT }}
        env:
          node_env: ${{ secrets.NODE_ENV }}
          main_url: ${{ secrets.MAIN_URL }}
          api_version: ${{ secrets.API_VERSION }}
          base_url: ${{ secrets.BASE_URL }}
          market_slug: ${{ secrets.MARKET_SLUG }}
          user_agent_product: ${{ secrets.USER_AGENT_PRODUCT }}
          internal_tcp_server_port: ${{ secrets.INTERNAL_TCP_SERVER_PORT }}
          display: ${{ secrets.DISPLAY }}
          port: ${{ secrets.PORT }}
          sentry_dsn: ${{ secrets.SENTRY_DSN }}
          default_external_tcp_cues_port: ${{ secrets.DEFAULT_EXTERNAL_TCP_CUES_PORT}
          
      - name: Run build
        run:  npm run build:linux
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: | 
            release-builds/installers
    
