name: Build Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Package
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 16
      - name: Install yarn
        run:  npm install --global yarn
      - name: Install Electron Packager
        run: npm i -g electron-packager
      - name: Install Electron Installer Debian
        run: npm i -g electron-installer-debian
      - name: Install fakeroot
        run: sh scripts/install.sh
      - name: Install node modules
        run:  npm i --legacy-peer-deps
      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
          ENV_NODE_ENV: ${{ secrets.NODE_ENV }}
          ENV_MAIN_URL: ${{ secrets.MAIN_URL }}
          ENV_API_VERSION: ${{ secrets.API_VERSION }}
          ENV_BASE_URL: ${{ secrets.BASE_URL }}
          ENV_MARKET_SLUG: ${{ secrets.MARKET_SLUG }}
          ENV_USER_AGENT_PRODUCT: ${{ secrets.USER_AGENT_PRODUCT }}
          ENV_INTERNAL_TCP_SERVER_PORT: ${{ secrets.INTERNAL_TCP_SERVER_PORT }}
          ENV_DISPLAY: ${{ secrets.DISPLAY }}
          ENV_PORT: ${{ secrets.PORT }}
          ENV_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          ENV_DEFAULT_EXTERNAL_TCP_CUES_PORT: ${{ secrets.DEFAULT_EXTERNAL_TCP_CUES_PORT }}
          
      - name: Run build
        run:  npm run build:linux
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: | 
            release-builds/installers
    
